[package]
name = "hara-wasm-raw"
version = "0.1.6"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.78"

[lib]
crate-type = ["cdylib"]

[features]
evaluation-journal = []
dev-trace = ["evaluation-journal"]
halc-encoder = []
hir-encoder = ["halc-encoder"]
bytecode-vm = []
tracing-jit = ["bytecode-vm"]

[dependencies]
sha2 = "0.10"
