[package]
name = "hara-values-echo"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
description = "Conformance Component for hara:values"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt = { version = "=0.44.0", features = ["bitflags"] }

[package.metadata.component]
package = "hara:values-echo"

[package.metadata.component.target]
path = "wit"
world = "echo"

[package.metadata.component.target.dependencies]
"hara:values" = { path = "wit/deps/hara-values" }
